import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const clients = [
  {
    id: 1,
    name: "John Doe",
    type: "Individual",
    email: "john@example.com",
    status: "Active",
    updatedBy: "Admin",
    createdAt: "2024-01-10",
    updatedAt: "2024-04-20",
  },
  {
    id: 2,
    name: "Alice Smith",
    type: "Company",
    email: "alice@example.com",
    status: "Inactive",
    updatedBy: "Admin",
    createdAt: "2024-02-15",
    updatedAt: "2024-03-18",
  },
  {
    id: 3,
    name: "Bob Johnson",
    type: "Individual",
    email: "bob@example.com",
    status: "Active",
    updatedBy: "Manager",
    createdAt: "2024-03-12",
    updatedAt: "2024-04-01",
  },
  {
    id: 4,
    name: "Charlie Brown",
    type: "Individual",
    email: "charlie@example.com",
    status: "Pending",
    updatedBy: "Admin",
    createdAt: "2024-04-01",
    updatedAt: "2024-04-22",
  },
  {
    id: 5,
    name: "Daisy Ridley",
    type: "Company",
    email: "daisy@example.com",
    status: "Active",
    updatedBy: "Manager",
    createdAt: "2024-01-25",
    updatedAt: "2024-03-30",
  },
  {
    id: 6,
    name: "Ethan Hunt",
    type: "Individual",
    email: "ethan@example.com",
    status: "Inactive",
    updatedBy: "Admin",
    createdAt: "2024-02-02",
    updatedAt: "2024-04-10",
  },
  {
    id: 7,
    name: "Fiona Gallagher",
    type: "Company",
    email: "fiona@example.com",
    status: "Pending",
    updatedBy: "Admin",
    createdAt: "2024-03-05",
    updatedAt: "2024-04-15",
  },
  {
    id: 8,
    name: "George Clooney",
    type: "Individual",
    email: "george@example.com",
    status: "Active",
    updatedBy: "Manager",
    createdAt: "2024-01-17",
    updatedAt: "2024-02-28",
  },
  {
    id: 9,
    name: "Hannah Baker",
    type: "Company",
    email: "hannah@example.com",
    status: "Active",
    updatedBy: "Admin",
    createdAt: "2024-03-22",
    updatedAt: "2024-04-18",
  },
  {
    id: 10,
    name: "Ian Somerhalder",
    type: "Individual",
    email: "ian@example.com",
    status: "Inactive",
    updatedBy: "Manager",
    createdAt: "2024-02-27",
    updatedAt: "2024-03-29",
  },
  {
    id: 11,
    name: "Jack Sparrow",
    type: "Company",
    email: "jack@example.com",
    status: "Active",
    updatedBy: "Admin",
    createdAt: "2024-01-19",
    updatedAt: "2024-03-22",
  },
  {
    id: 12,
    name: "Kate Winslet",
    type: "Individual",
    email: "kate@example.com",
    status: "Pending",
    updatedBy: "Manager",
    createdAt: "2024-03-10",
    updatedAt: "2024-04-12",
  },
  {
    id: 13,
    name: "Leonardo DiCaprio",
    type: "Company",
    email: "leo@example.com",
    status: "Active",
    updatedBy: "Admin",
    createdAt: "2024-01-30",
    updatedAt: "2024-03-26",
  },
  {
    id: 14,
    name: "Mia Wallace",
    type: "Individual",
    email: "mia@example.com",
    status: "Inactive",
    updatedBy: "Admin",
    createdAt: "2024-02-05",
    updatedAt: "2024-04-05",
  },
  {
    id: 15,
    name: "Noah Centineo",
    type: "Company",
    email: "noah@example.com",
    status: "Active",
    updatedBy: "Manager",
    createdAt: "2024-03-15",
    updatedAt: "2024-04-20",
  },
  {
    id: 16,
    name: "Olivia Wilde",
    type: "Individual",
    email: "olivia@example.com",
    status: "Active",
    updatedBy: "Admin",
    createdAt: "2024-02-20",
    updatedAt: "2024-03-25",
  },
  {
    id: 17,
    name: "Paul Walker",
    type: "Company",
    email: "paul@example.com",
    status: "Pending",
    updatedBy: "Admin",
    createdAt: "2024-03-01",
    updatedAt: "2024-04-10",
  },
  {
    id: 18,
    name: "Quentin Tarantino",
    type: "Individual",
    email: "quentin@example.com",
    status: "Inactive",
    updatedBy: "Manager",
    createdAt: "2024-01-12",
    updatedAt: "2024-02-25",
  },
  {
    id: 19,
    name: "Rachel Green",
    type: "Company",
    email: "rachel@example.com",
    status: "Active",
    updatedBy: "Admin",
    createdAt: "2024-03-19",
    updatedAt: "2024-04-16",
  },
  {
    id: 20,
    name: "Steve Rogers",
    type: "Individual",
    email: "steve@example.com",
    status: "Active",
    updatedBy: "Manager",
    createdAt: "2024-01-29",
    updatedAt: "2024-03-15",
  },
];
